### ISSUE TITLE
Check if the output already exists before running a command

### ISSUE THREAD

**Issue by javierucm** [javierucm/decont#1]
Hola! Tengo una pregunta sobre el punto de bonus siguiente:

 "Check if the output already exists before running a command. If it exists, display a message, skip the operation, and continue."

Me gustaría saber si es necesario hacer esa comprobación antes de descargar (wget) y antes de descomprimir (gunzip). 
Para el caso del trimmed y de la indexación veo claro que sí que es necesario incluirlo, pero para los del script de download.sh no lo veo tan claro.

En concreto para wget , uso el parámetro -nc  que comprueba la existencia del mismo antes de descargarlo, con lo que es lo que se está pidiendo, con al excepción que se llama desde dentro del comando y no antes.

Por otro lado gunzip, por defecto, pregunta al usuario si desea descomprimirlo en el caso de que ya existan los archivos, que no es exactamente lo que se pide, pero también me parece correcto, ya que no descomprime por defecto nada.

Por otro lado, entiendo que la sección del Log no habría tampoco que hacer una comprobación, ni en el cleanup, ya que en ninguno de los casos parece demasiado lógico. Pero si no es así, házmelo saber por favor.

Muchas gracias!!

**Comment by tdido** [comment]
Si resolvés la descarga con wget y con parámetros obtenés el mismo resultado entonces perfecto, no hace falta comprobar.

El tema de depender de una interacción con el usuario como en el caso que describís de gzip sí que sería mejor evitarlo, ya que queremos que esté todo automatizado.

En los logs no hace falta comprobar nada ya que simplemente acumulan la información.

**Comment by javierucm** [comment]
Muchas gracias!! :-)

**Comment by javierucm** [comment]
Una última y sencilla pregunta, que ya solo me quedan detalles.

Cuando ejecutamos el comando seqkit en el que limpiamos el archivo contaminents.fasta, de acuerdo con la estructura del Readme, creo entender que hemos de sobreescribir ese mismo archivo contaminents.fasta, con lo que no sería posible, en una segunda ejecución, comprobar si ese comando se ha ejecutado o no antes. ¿Es necesario por tanto hacer la comprobación antes de la ejecución del seqkit? ¿O no haría falta y siempre se ejecutaría?
Obviamente hay otras opciones para comprobar si se hizo la limpieza o no, como crear el archivo ya filtrado con otro nombre, dejar un archivo temporal, o mirarlo en un log, pero no sé si es el propósito de esta práctica o no es necesario hacerlo.

Muchas gracias!

**Comment by tdido** [comment]
Hm, buen punto. Veo que olvidé actualizar la salida del tree para mostrar que mi idea original era crear un archivo con otro nombre al filtrar. De todas maneras cualquiera de las soluciones que proponés es válida. Por las razones que decís optaría por no sobreescribir para que sea todo re-ejecutable.

**Comment by javierucm** [comment]
Qué celeridad!! Gracias!!
